spec:
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://github.com/phclark/k8s-demo.git
    path: charts/platform
    targetRevision: main
  syncPolicy:
    automated: {}