apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: platform
  namespace: argocd
spec:
  destination:
    server: https://kubernetes.default.svc
  source:
    repoURL: https://github.com/phclark/k8s-demo.git
    targetRevision: HEAD
    path: charts/platform