apiVersion: argoproj.io/v1alpha1
kind: application
name: platform-chart
version: 0.0.1
appVersion: 0.0.1
spec:
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://github.com/phclark/k8s-demo.git
    targetRevision: main
syncPolicy:
    automated: {}