destination:
  namespace: argocd
  server: https://kubernetes.default.svc
project: default
source:
  repoURL: https://github.com/phclark/k8s-demo.git
  targetRevision: main

syncPolicy:
    automated: {}

# predefined services can be enabled and configured easily
monitoring:
  grafana:
    enabled: false
  loki:
    enabled: false
  prometheus: 
    enabled: false

services: []
      