syncPolicy:
    automated: {}

# predefined services can be enabled and configured easily
monitoring:
  grafana:
    enabled: false
  loki:
    enabled: false
  prometheus: 
    enabled: false

services: []
      