affinity: {}
image:
  pullPolicy: IfNotPresent
  repository: demo-api
  tag: 0.0.13
ingress:
  annotations:
    kubernetes.io/ingress.class: alb
    kubernetes.io/tls-acme: 'true'
  enabled: true
  hosts:
  - api.grainfreewoodworks.com
  path: /demo
  tls: []
nodeSelector: {}
replicaCount: 1
resources: {}
service:
  port: 80
  type: ClusterIP
tolerations: []
