affinity: {}
image:
  pullPolicy: IfNotPresent
  repository: 767534018423.dkr.ecr.us-east-1.amazonaws.com/demo-api
  tag: 0.0.2
ingress:
  annotations:
    kubernetes.io/ingress.class: alb
    kubernetes.io/tls-acme: 'true'
  enabled: true
  hosts:
  - api.grainfreewoodworks.com
  path: /demo
  tls: []
nodeSelector: {}
replicaCount: 1
resources: {}
service:
  port: 8000
  type: ClusterIP
tolerations: []
