environment: dev

namespaces:
  - api

# predefined services can be enabled and configured easily
monitoring:
  grafana:
    enabled: true
  loki:
    enabled: true
  prometheus: 
    enabled: true

elasticcloud:
  enabled: true
  nodeSets:
    default:
      count: 2

argoevents:
  enabled: true
  
# Services list allows arbitrary charts to be deployed and configured
services:
  - chart: demo-api
    namespace: api
    values:
      replicaCount: 1
      ingress:
        enabled: true
        hostname: api.grainfreewoodworks.com
  - chart: demo-api
    namespace: api
    nameOverride: demo-api-beta1 
    valueFiles: 
      - ../../environments/dev/values/demo-api-beta1.yaml # relative to charts/demo-api
  - chart: workflows
    namespace: argo-workflows
    version: 0.0.1


  
