environment: tst

namespaces:
  - tst-api

# predefined services can be enabled and configured easily
monitoring:


elasticcloud:
  enabled: false
  nodeSets:
    default:
      count: 2

argoevents:
  enabled: false
  
# Services list allows arbitrary charts to be deployed and configured
services:
  - chart: demo-api
    namespace: tst-api
    values:
      replicaCount: 1
      ingress:
        enabled: true
        hostname: api.grainfreewoodworks.com
  - chart: demo-api
    namespace: tst-api
    nameOverride: demo-api-beta1 
    valueFiles: 
      - ../../environments/tst/values/demo-api-beta1.yaml # relative to charts/demo-api


  
