# {{ if .Values.argoevents.enabled and false }}
# apiVersion: argoproj.io/v1alpha1
# kind: Application
# metadata:
#   name: argo-events
#   namespace: argocd
#   finalizers:
#   - resources-finalizer.argocd.argoproj.io
# spec:
#   destination:
#     namespace: argo-events
#     server: {{ .Values.destination.server }}
#   project: {{ .Values.project }}
#   source:
#     chart: argo-events
#     repoURL: https://argoproj.github.io/argo-helm
#     targetRevision: 1.13.0
#   syncPolicy:
#     automated: {}
# ---
# apiVersion: v1
# kind: Namespace
# metadata:
#   name: argo-events
# {{ end }}