{{ if .Values.elasticcloud.enabled }}
apiVersion: v1
kind: Namespace
metadata:
  name: elastic
---
apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: elasticsearch-cluster
  namespace: elastic
spec:
  version: 8.1.3
  nodeSets:
  - name: default
    count: {{ .Values.elasticcloud.nodeSets.default.count}}
    config:
      node.store.allow_mmap: false
{{ end }}