{{ if .Values.elasticcloud.enabled }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: elastic-cloud-crds
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: elastic-system
    server: {{ .Values.destination.server }}
  project: {{ .Values.project }}
  source:
    chart: eck-operator-crds
    repoURL: https://helm.elastic.co
    targetRevision: 2.1.0
  syncPolicy:
    automated: {}
{{ end }}