{{ if .Values.monitoring.grafana.enabled }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: monitoring
    server: {{ .Values.destination.server }}
  project: {{ .Values.project }}
  source:
    chart: grafana/grafana
    repoURL: https://grafana.github.io/helm-charts
    targetRevision: 6.26.6
  syncPolicy:
    automated: {}
{{ end }}