{{ if .Values.monitoring.prometheus.enabled }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: monitoring
    server: {{ .Values.destination.server }}
  project:  {{ .Values.project }}
  source:
    path: charts/prometheus
    repoURL: {{ .Values.source.repoURL }}
    targetRevision: {{ .Values.source.targetRevision }}
  syncPolicy:
    automated: {}
{{ end }}