apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: awscli
spec:
  executor:
    serviceAccountName: argo-workflows-actions
  entrypoint: awscli
  arguments:
  templates:
    - name: awscli
      container:
        image: jshimko/kube-tools-aws:latest
        command: ["ls","-al","/var/run/secrets/kubernetes.io/serviceaccount"]
