apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: awscli
  namespace: argo-workflows
spec:
  entrypoint: awscli
  arguments:
  templates:
    - name: awscli
      serviceAccountName: argo-workflows-actions
      script:
        image: jshimko/kube-tools-aws:latest
        command: [/bin/bash]
        source: |
          aws s3 ls
          kubectl get namespaces