apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: awscli
spec:
  executor:
    serviceAccountName: argo-workflows-actions
  entrypoint: awscli
  arguments:
    parameters:
      - name: command
        value: aws s3 ls
  templates:
    - name: awscli
      inputs:
        parameters:
          - name: command
      container:
        image: jshimko/kube-tools-aws:latest
        command: [/bin/bash]
        args: {{ split " " `{{inputs.parameters.command}}` }}
        