apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: awscli
spec:
  entrypoint: awscli
  arguments:
    parameters:
      - name: command
        value: s3 ls
  templates:
    - name: awscli
      inputs:
        parameters:
          - name: command
      container:
        image: jshimko/kube-tools-aws:latest
        command: [/bin/bash]
        args: ["{{`{{inputs.parameters.command.split(' ')}}`}}"]  # Argo Workflows templating needs to be escaping from Helm
      env:
      - name: MYSECRETPASSWORD  # name of env var
        valueFrom:
          secretKeyRef:
            name: my-secret     # name of an existing k8s secret
            key: mypassword     # 'key' subcomponent of the secret
      volumeMounts:
      - name: my-secret-vol     # mount file containing secret at /secret/mountpath
        mountPath: "/secret/mountpath"