apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: awscli
spec:
  entrypoint: awscli
  arguments:
  templates:
    - name: awscli
      serviceAccountName: argo-workflows-actions
      container:
        image: jshimko/kube-tools-aws:latest
        command: ["aws","s3","ls"]
