apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: log
  namespace: argo-workflows
spec:
  dependencies:
    - name: test-dep
      eventSourceName: webhook
      eventName: example
  triggers:
    - template:
        name: log-trigger
        log:
          intervalSeconds: 20