apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: demo-api
  name: ingress-demo-api
spec:
  rules:
  - host: demo-api.localhost
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: demo-api
            port:
              number: 80
  ingressClassName: nginx
  