apiVersion: v1
kind: Secret
metadata:
  name: ${environment}-secret
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: cluster
type: Opaque
stringData:
  name: ${environment}
  server: ${kubernetes_endpoint}
  config: |
    {
      "bearerToken": "${token}",
      "tlsClientConfig": {
        "insecure": false,
        "caData": "${cert}"
      }
    }