apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: platform-${environment}
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: argocd
    name: ${environment}
  project: ${environment}
  source:
    repoURL: https://github.com/phclark/k8s-demo.git
    path: charts/platform
    targetRevision: main
    helm:
      valueFiles:
      - ../../environments/${environment}/values.yml # relative to charts/platform
  syncPolicy:
      automated:  
        prune: true
        selfHeal: true
