{
 "title": "API APM Metrics",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "HTTP Request Volume",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "targets": [
    { "expr": "rate(http_requests_total[5m])" }
   ]
  },
  {
   "title": "HTTP Request Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "histogram_quantile(0.90, sum(rate(http_request_duration_seconds_bucket{app=\"demo-api\",handler=\"/\"}[5m])) by (le))"
    }
   ]
  },
  {
   "title": "Error Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    { "expression": "$Errors / $Total * 100", "type": "math" }
   ]
  }
 ]
}