# Deploys Terraform configurations on changes

name: Terraform CD

on:
  push:
    branches: 
      - main
    paths:
      - terraform/projects/**

  workflow_dispatch:

env:
  environment: dev
  AWS_REGION: us-east-1

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@13d241b293754004c80624b5567555c4a39ffbe3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}
      - uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.1.4
      - uses: bridgecrewio/checkov-action@master
        with:
          quiet: true 
          directory: terraform/
          framework: terraform
      - name: Deploy Cluster project
        run: |
          cd terraform
          ../scripts/symlink.sh
          cd projects/cluster/environments/${{env.environment}}
          terraform init
          terraform validate
          terraform plan -out tf.plan
          terraform apply tf.plan
      - name: Deploy k8s_core project
        run: |
          cd terraform
          ../scripts/symlink.sh
          cd projects/k8s_core/environments/${{env.environment}}
          terraform init
          terraform validate
          terraform plan -out tf.plan
          terraform apply tf.plan
          
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v19

      - name: List all changed files
        run: |
          for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
            echo "$file was changed"
          done