# Deploys Terraform configurations on changes

name: Terraform CI

on:
  push:
    branches: 
      - main
    paths:
      - terraform/modules/**

  workflow_dispatch:

env:
  environment: dev
  AWS_REGION: us-east-1

jobs:
  generate-matrix:
    runs-on: ubuntu-latest
    outputs:
      modules: ${{ steps.generate-matrix.outputs.matrix }}
    steps:
      - uses: actions/checkout@v2
      - name: Generate matrix
        id: generate-matrix
        uses: hellofresh/action-changed-files@v2
        with:
          pattern: terraform/modules/(?P<module>[^/]+)

  build:
    needs: generate-matrix
    strategy:
      matrix: ${{ fromJson(needs.generate-matrix.outputs.modules) }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@13d241b293754004c80624b5567555c4a39ffbe3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}
      - uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.1.4
          terraform_wrapper: false
      - uses: actions/setup-go@v3
        with:
          go-version: '^1.17'
      - uses: actions/cache@v3
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - run: go version
      - uses: bridgecrewio/checkov-action@master
        with:
          quiet: true 
          directory: terraform/modules/${{ matrix.module }}
          framework: terraform
      - id: terratest
        working-directory: terraform/modules/${{ matrix.module }}
        run: |
          go test -v ./test
