environment: dev

namespaces:
  - api

# predefined services can be enabled and configured easily
monitoring:
  grafana:
    enabled: true
  loki:
    enabled: true
  prometheus: 
    enabled: true

# Services list allows arbitrary charts to be deployed and configured
services:
  - chart: demo-api
    namespace: api
    values:
      replicaCount: 1
      ingress:
        annotations:
          kubernetes.io/ingress.class: alb
          kubernetes.io/tls-acme: 'true'
        enabled: true
        hosts:
          - api.grainfreewoodworks.com
  - chart: demo-api
    namespace: api
    nameOverride: demo-api-beta1 
    valueFiles: 
      - values/demo-api-beta1.yml
  - chart: workflows
    namespace: argo-workflows
    version: 0.0.1


  
